[IV-24-25] Objetivo 0
joselopez10014/OrganizadorVJ pull request #2
Opened 2024-10-01 17:37 UTC by joselopez10014

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Si, para que sea accesible para multiples usuarios
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
Se ha incluido la configuración y el enlace
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
Sería necesario que el usuario introduzca algunos datos para que la aplicación pueda funcionar
* [x] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?
He seguido la lista

2024-10-02 15:23 UTC, JJ requested changes
Realmente la metodología del primer día, al que asististe, os debería haber ayudado a encontrar un problema adecuado. No sé si alguna de las dos cosas que has puesto fue lo que propusiste el primer día. En cualquier caso sería conveniente que siguieras esa metodología para encontrar un problema con el que puedas trabajar. Recuerda que lo esencial es entender y aplicar metodologías, no tener una idea brillante que pueda ser, de casualidad, adecuada.

2024-10-02 15:23 UTC, JJ commented on README.md
> +-No sabemos cuando podriamos reunirnos debido a las diferencias en nuestros horarios.
¿De qué forma esta lógica de negocio va más allá de almacenar y buscar?

2024-10-02 15:23 UTC, JJ commented on README.md
> +-Al no saber que juegos tiene cada miembro del grupo solemos tener problemas para saber a que podemos jugar
Y esto, a parte de ser un problema diferente, ¿cómo sería diferente de almacenar y buscar?

2024-10-03 11:17 UTC, JJ requested changes
Por favor, comprueba dentro de repositorios de datos abiertos, o de páginas web disponibles públicamente, si hubiera algún dato semi-difícil de extraer con el que pudieras trabajar. También te animo a que vuelvas a usar la metodología de design thinking, teniendo siempre en mente lo que es posible dentro de la asignatura.

2024-10-03 11:17 UTC, JJ commented on README.md
> +Me han diagnosticado diabetes y ahora debo de empezar a ponerme insulina varias veces a lo largo del día.
Una vez más depende de factores externos. Como dice el guión, depender de factores externos y su comprobación queda fuera del control de la asignatura.

2024-10-03 11:17 UTC, JJ commented on README.md
> +El problema es que me resulta dificil analizar mis valores de glucosa y usarlos para calcular un ratio adecuado para mi.
No entiendo muy bien cuál es el problema, pero en caso de que esto comporte aplicar algún algoritmo estamos hablando de datos que son difíciles de obtener y que en todo caso no serían adecuados para un problema en la nube, sino algo que se pudiera llevar en un móvil conectado a un sensor. No tiene ningún sentido que se cree una aplicación cliente-servidor para esto.

2024-10-03 11:18 UTC, joselopez10014 commented
@JJ Listo para revisión

2024-10-10 10:40 UTC, joselopez10014 commented
@JJ Listo para revisión

2024-10-10 10:53 UTC, JJ approved these changes
👏

2024-10-10 11:10 UTC, merged